### ISSUE TITLE
Urgent - Why not preview of icon in editor after insertion?

### ISSUE THREAD

**Issue by xcelpixel** [EvanHerman/WP-SVG-Icons-WordPress-Plugin#4]
Hi Evan, Great plugin. My question is why it doesn't render any preview of added icon in the editor? It shows only shortcode? 

Let me know if anything you have in mind.

Thanks

**Comment by EvanHerman** [comment]
The WP Editor doesn't render the svg because it doesn't know how to handle the shortcode. WordPress doesn't currently have an API to specify how shortcodes should be parsed. Moving forward they have a few things in development to allow for this.

The most promising is shortcake php.

https://github.com/fusioneng/Shortcake

I haven't implemented or integrated shortcake with any plugins I currently develop, but as it gets closer to being in core I certainly will as I know previewing the short code is fairly important. During development this thought crossed my mind but at the time there was no reasonable solution.

http://wptavern.com/shortcake-is-now-a-wordpress-feature-plugin


Thanks,
Evan

**Comment by xcelpixel** [comment]
Will check it out. There must an option to add SVG directly into pack of icons. icomoon Application is pretty advanced to generate things.

Thanks Evan.

**Comment by xcelpixel** [comment]
Hi Evan,
I need some help regarding registering your shortcodes for Wp Svg Icon shortcodes. I don't know how to do this. Let me know if you can guide men. 
That would be great and much appreciated. 

Thanks

**Comment by EvanHerman** [comment]
Hi,

I'm not entirely sure what you are asking. The plugin is intended to be activated, and then used from within a page or post. If you are still having issues and need additional help, feel free to purchase the pro version and submit a priority support request.


Thanks again,
Evan
